### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by elhananjair** [ukarim/smscsim#11]
I am trying to build the application, I am having a problem:

```
Error: LinkageError occurred while loading main class smscsim.Main
        java.lang.UnsupportedClassVersionError: smscsim/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

```

**Comment by ukarim** [comment]
Hi,You have compiled the smscsim with java 21, but tried to run it with java 17. Just use java21 when doing `java smscsim.Main`or you can use prebuilt docker image`docker run -p 2775:2775 -p 12775:12775 ukarim/smscsim`Sent from my Galaxy

**Comment by elhananjair** [comment]
@ukarim thank you so much I executed with docker and it worked for me.
