### ISSUE TITLE
No session found for systemId: []

### ISSUE THREAD

**Issue by ankit22550** [ukarim/smscsim#2]
i am using SMSC simulator but i am getting below error.

**No session found for systemId: []**

**Comment by ukarim** [comment]
@ankit22550 it seems there is no active smpp session out there. You need some smpp client connected to the smscsim.
If you are trying to send MO message to your smpp client application then you need to:
1. establish a smpp connection to the smscsim
2. select a system id of your smpp client in the web form
![image](https://user-images.githubusercontent.com/12429084/103228804-d9365400-495b-11eb-9fc7-70140079e0e7.png)
