### ISSUE TITLE
go test failing

### ISSUE THREAD

**Issue by divyanshu0045** [ukarim/smscsim#4]
[root@localhost smscsim]# go test
expected: [0000003b000000050000000000000066736d736373696d000000373730313231313030303000000031303031000100000000000008000454657374]
actual: [0000003b000000050000000000000066736d736373696d000000373730313231313030303000000031303031000_000000000000000_000454657374]

--- FAIL: TestDeliverSmPduBytes (0.00s)
    smsc_test.go:54: PDU with string body incorrectly encoded
FAIL
exit status 1
FAIL    github.com/ukarim/smscsim       0.003s

**Comment by ukarim** [comment]
@divyanshu0045 fixed. thanks!
